import functions as f
import numpy as np


# a) demonstrating that rd(conv(ld(R))) is the same as rd(ld(conv(R))) for all 11 relationships
def prt2_a_disjoin():
    disjoin = np.array([[0, 0, 1], [0, 0, 1], [1, 1, 1]])

    print("rd(conv(ld(R)))")
    print("For: DISJOIN")
    print(disjoin)
    x = f.lft_dual(disjoin)
    print("-> to contains with a left dual.")
    print(x)
    y = f.converse(x)
    print("-> to inside with the converse.")
    print(x)
    z = f.rt_dual(y)
    print("-> to DISJOIN with a right dual.")
    print(z)

    print("rd(ld(conv(R)))")
    disjoin = np.array([[0, 0, 1], [0, 0, 1], [1, 1, 1]])
    print('For: DISJOIN')
    print(disjoin)
    y = f.converse(disjoin)
    print('-> to disjoin with the converse.')
    print(y)
    y = f.lft_dual(y)
    print('-> to contains with a left dual.')
    print(y)
    z = f.rt_dual(y)
    print("-> to EMBRACE with a right dual.")
    print(z)
    print("\n")


def prt2_a_embrace():
    embrace = np.array([[1, 1, 1], [1, 0, 0], [1, 0, 0]])

    print("rd(conv(ld(R)))")
    print("For: EMBRACE")
    print(embrace)
    x = f.lft_dual(embrace)
    print("-> to inside with a left dual.")
    print(x)
    y = f.converse(x)
    print("-> to contains with the converse.")
    print(x)
    z = f.rt_dual(y)
    print("-> to EMBRACE with a right dual.")
    print(z)

    print("rd(ld(conv(R)))")
    embrace = np.array([[1, 1, 1], [1, 0, 0], [1, 0, 0]])
    print('For: EMBRACE')
    print(embrace)
    y = f.converse(embrace)
    print('-> to embrace with the converse.')
    print(y)
    y = f.lft_dual(y)
    print('-> to inside with a left dual.')
    print(y)
    z = f.rt_dual(y)
    print("-> to DISJOIN with a right dual.")
    print(z)
    print("\n")


def prt2_a_attach():
    attach = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])

    print("rd(conv(ld(R)))")
    print("For: ATTACH")
    print(attach)
    x = f.lft_dual(attach)
    print("-> to equals with a left dual.")
    print(x)
    y = f.converse(x)
    print("-> to equals with the converse.")
    print(x)
    z = f.rt_dual(y)
    print("-> to ATTACH with a right dual.")
    print(z)

    print("rd(ld(conv(R)))")
    attach = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
    print('For: ATTACH')
    print(attach)
    y = f.converse(attach)
    print('-> to attach with the converse.')
    print(y)
    y = f.lft_dual(y)
    print('-> to equals with a left dual.')
    print(y)
    z = f.rt_dual(y)
    print("-> to ATTACH with a right dual.")
    print(z)
    print("\n")


def prt2_a_entwined():
    entwined = np.array([[1, 1, 1], [1, 1, 0], [1, 0, 0]])

    print("rd(conv(ld(R)))")
    print("For: ENTWINED")
    print(entwined)
    x = f.lft_dual(entwined)
    print("-> to coveredBy with a left dual.")
    print(x)
    y = f.converse(x)
    print("-> to covers with the converse.")
    print(x)
    z = f.rt_dual(y)
    print("-> to ENTWINED with a right dual.")
    print(z)

    print("rd(ld(conv(R)))")
    entwined = np.array([[1, 1, 1], [1, 1, 0], [1, 0, 0]])
    print('For: ENTWINED')
    print(entwined)
    y = f.converse(entwined)
    print('-> to entwined with the converse.')
    print(y)
    y = f.lft_dual(y)
    print('-> to coveredBy with a left dual.')
    print(y)
    z = f.rt_dual(y)
    print("-> to MEET with a right dual.")
    print(z)
    print("\n")


def prt2_a_meet():
    meet = np.array([[0, 0, 1], [0, 1, 1], [1, 1, 1]])

    print("rd(conv(ld(R)))")
    print("For: MEET")
    print(meet)
    x = f.lft_dual(meet)
    print("-> to covers with a left dual.")
    print(x)
    y = f.converse(x)
    print("-> to coveredBy with the converse.")
    print(x)
    z = f.rt_dual(y)
    print("-> to MEET with a right dual.")
    print(z)

    print("rd(ld(conv(R)))")
    meet = np.array([[0, 0, 1], [0, 1, 1], [1, 1, 1]])
    print('For: MEET')
    print(meet)
    y = f.converse(meet)
    print('-> to meet with the converse.')
    print(y)
    y = f.lft_dual(y)
    print('-> to covers with a left dual.')
    print(y)
    z = f.rt_dual(y)
    print("-> to ENTWINED with a right dual.")
    print(z)
    print("\n")


def prt2_a_overlap():
    overlap = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

    print("rd(conv(ld(R)))")
    print("For: OVERLAP")
    print(overlap)
    x = f.lft_dual(overlap)
    print("-> to overlap with a left dual.")
    print(x)
    y = f.converse(x)
    print("-> to overlap with the converse.")
    print(x)
    z = f.rt_dual(y)
    print("-> to OVERLAP with a right dual.")
    print(z)

    print("rd(ld(conv(R)))")
    overlap = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
    print('For: OVERLAP')
    print(overlap)
    y = f.converse(overlap)
    print('-> to overlap with the converse.')
    print(y)
    y = f.lft_dual(y)
    print('-> to overlap with a left dual.')
    print(y)
    z = f.rt_dual(y)
    print("-> to OVERLAP with a right dual.")
    print(z)
    print("\n")


def prt2_a_coveredBy():
    coveredBy = np.array([[1, 0, 0], [1, 1, 0], [1, 1, 1]])
    print("rd(conv(ld(R)))")
    print("For: COVEREDBY")
    print(coveredBy)
    x = f.lft_dual(coveredBy)
    print("-> to entwined with a left dual.")
    print(x)
    y = f.converse(x)
    print("-> to entwined with the converse.")
    print(x)
    z = f.rt_dual(y)
    print("-> to COVERS with a right dual.")
    print(z)

    print("rd(ld(conv(R)))")
    coveredBy = np.array([[1, 0, 0], [1, 1, 0], [1, 1, 1]])
    print('For: COVEREDBY')
    print(coveredBy)
    y = f.converse(coveredBy)
    print('-> to covers with the converse.')
    print(y)
    y = f.lft_dual(y)
    print('-> to meet with a left dual.')
    print(y)
    z = f.rt_dual(y)
    print("-> to coveredBy with a right dual.")
    print(z)
    print("\n")


def prt2_a_covers():
    covers = np.array([[1, 1, 1], [0, 1, 1], [0, 0, 1]])
    print("rd(conv(ld(R)))")
    print("For: COVERS")
    print(covers)
    x = f.lft_dual(covers)
    print("-> to meet with a left dual.")
    print(x)
    y = f.converse(x)
    print("-> to meet with the converse.")
    print(x)
    z = f.rt_dual(y)
    print("-> to COVEREDBY with a right dual.")
    print(z)

    print("rd(ld(conv(R)))")
    covers = np.array([[1, 1, 1], [0, 1, 1], [0, 0, 1]])
    print('For: COVERS')
    print(covers)
    y = f.converse(covers)
    print('-> to coveredBy with the converse.')
    print(y)
    y = f.lft_dual(y)
    print('-> to entwined with a left dual.')
    print(y)
    z = f.rt_dual(y)
    print("-> to COVERS with a right dual.")
    print(z)
    print("\n")


def prt2_a_inside():
    inside = np.array([[1, 0, 0], [1, 0, 0], [1, 1, 1]])
    print("rd(conv(ld(R)))")
    print("For: INSIDE")
    print(inside)
    x = f.lft_dual(inside)
    print("-> to embrace with a left dual.")
    print(x)
    y = f.converse(x)
    print("-> to embrace with the converse.")
    print(x)
    z = f.rt_dual(y)
    print("-> to CONTAINS with a right dual.")
    print(z)

    print("rd(ld(conv(R)))")
    inside = np.array([[1, 0, 0], [1, 0, 0], [1, 1, 1]])
    print('For: INSIDE')
    print(inside)
    y = f.converse(inside)
    print('-> to contains with the converse.')
    print(y)
    y = f.lft_dual(y)
    print('-> to disjoint with a left dual.')
    print(y)
    z = f.rt_dual(y)
    print("-> to INSIDE with a right dual.")
    print(z)
    print("\n")


def prt2_a_equals():
    equals = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

    print("rd(conv(ld(R)))")
    print("For: EQUALS")
    print(equals)
    x = f.lft_dual(equals)
    print("-> to attach with a left dual.")
    print(x)
    y = f.converse(x)
    print("-> to attach with the converse.")
    print(x)
    z = f.rt_dual(y)
    print("-> to EQUALS with a right dual.")
    print(z)

    print("rd(ld(conv(R)))")
    equals = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
    print('For: EQUALS')
    print(equals)
    y = f.converse(equals)
    print('-> to equals with the converse.')
    print(y)
    y = f.lft_dual(y)
    print('-> to attach with a left dual.')
    print(y)
    z = f.rt_dual(y)
    print("-> to EQUALS with a right dual.")
    print(z)
    print("\n")


def prt2_a_contains():
    contains = np.array([[1, 1, 1], [0, 0, 1], [0, 0, 1]])

    print("rd(conv(ld(R)))")
    print("For: CONTAINS")
    print(contains)
    x = f.lft_dual(contains)
    print("-> to disjoint with a left dual.")
    print(x)
    y = f.converse(x)
    print("-> to disjoint with the converse.")
    print(x)
    z = f.rt_dual(y)
    print("-> to INSIDE with a right dual.")
    print(z)

    print("rd(ld(conv(R)))")
    contains = np.array([[1, 1, 1], [0, 0, 1], [0, 0, 1]])
    print('For: CONTAINS')
    print(contains)
    y = f.converse(contains)
    print('-> to inside with the converse.')
    print(y)
    y = f.lft_dual(y)
    print('-> to embrace with a left dual.')
    print(y)
    z = f.rt_dual(y)
    print("-> to CONTAINS with a right dual.")
    print(z)
    print("\n")
